# Generated by Django 4.2.7 on 2023-11-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('interests', models.TextField(blank=True, default='idk')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_smoke', models.BooleanField(default=False)),
                ('is_profcom', models.BooleanField(default=True)),
            ],
        ),
    ]
